productslist = [
  {
    '_id': '1',
    'name': 'Elegant Wooden Chair',
    'image': '/images/chair1.jpeg',
    'description': 'A beautifully crafted wooden chair that adds elegance to any room. Perfect for the living room or study.',
    'brand': 'Furniture Co.',
    'category': 'livingroom',
    'price': '89.99',
    'countInStock': '10',
    'rating': '4.5',
    'numReviews': '12',
  },
  {
    '_id': '2',
    'name': 'Modern Sofa Set',
    'image': '/images/sofa1.jpeg',
    'description': 'A stylish and comfortable sofa set that is perfect for lounging and entertaining guests.',
    'brand': 'Home Comfort',
    'category': 'livingroom',
    'price': '599',
    'countInStock': '0',
    'rating': '4.0',
    'numReviews': '8',
  },
  {
    '_id': '3',
    'name': 'Classic Wooden Dining Table',
    'image': '/images/sofa1.jpeg',
    'description': 'A sturdy and classic dining table that can accommodate the whole family for meals together.',
    'brand': 'Table Makers',
    'category': 'dining',
    'price': '929',
    'countInStock': '5',
    'rating': '3',
    'numReviews': '12',
  },
  {
    '_id': '4',
    'name': 'Cozy Recliner Chair',
    'image': '/images/playstation.jpg',
    'description': 'Enjoy your favorite books or movies in comfort with this plush recliner chair.',
    'brand': 'Relax Furniture',
    'category': 'livingroom',
    'price': '399',
    'countInStock': '11',
    'rating': '5',
    'numReviews': '12',
  },
  {
    '_id': '5',
    'name': 'Stylish Office Desk',
    'image': '/images/mouse.jpg',
    'description': 'A modern office desk designed for productivity and style, perfect for any workspace.',
    'brand': 'Office Essentials',
    'category': 'office',
    'price': '49',
    'countInStock': '7',
    'rating': '3.5',
    'numReviews': '10',
  },
  {
    '_id': '6',
    'name': 'Vintage Bookshelf',
    'image': '/images/alexa.jpg',
    'description': 'A charming vintage bookshelf that brings character and organization to your living space.',
    'brand': 'Classic Decor',
    'category': 'livingroom',
    'price': '29',
    'countInStock': '0',
    'rating': '4',
    'numReviews': '12',
  },
];
