# Generated by Django 5.1.2 on 2024-10-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_modelfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modelFile',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
    ]
